// 自動生成（docs/業務詳細.xlsx を正規化＋既存テンプレ補完）。受注区分→業務→タスク(=作業)。
// owner 既定は全て '自社'、hint は実施者割合/備考。再生成で上書きされ得る。

import type { TabKey } from '@/components/features/cases/CaseTabs'

// 「紹介のみ」は自社手続きなしの区分（業務・作業は持たず、他事業者紹介で紹介先を埋める）。
export const ORDER_CATEGORIES = ['手続き一式','登記','遺言','信託','放棄','調停','検認','後見','契約書','執行','紹介のみ'] as const
// 自社で行う相続手続きが無い区分（業務・作業を出さず、紹介先入力に切り替える）
export const REFERRAL_ONLY_CATEGORY = '紹介のみ'
export type OrderCategory = (typeof ORDER_CATEGORIES)[number]

export const GYOMU_TAB: Record<string, TabKey | undefined> = {
  '戸籍': 'deceased',
  '相関図': 'deceased',
  '法定相続情報取得': 'deceased',
  '不動産': 'assets',
  '金融資産': 'assets',
  '目録': 'assets',
  '協議書': 'division',
  '登記': 'registration',
  '解約': 'cancellation',
  '手紙': undefined,
  '遺言作成': 'will',
  '信託契約書作成': 'trust',
  '放棄手続き': 'renunciation',
  '調停手続き': 'mediation',
  '検認手続き': 'probate',
  '後見手続き': 'guardianship',
  '契約書作成': 'contractProc',
  '執行通知': undefined,
}
export const GYOMU_ALL = ['戸籍', '相関図', '法定相続情報取得', '不動産', '金融資産', '目録', '協議書', '登記', '解約', '手紙', '遺言作成', '信託契約書作成', '放棄手続き', '調停手続き', '検認手続き', '後見手続き', '契約書作成', '執行通知']

export type ServiceRow = { category: OrderCategory; gyomu: string; task: string; owner: '自社' | '依頼者'; hint?: string }

export const SERVICE_ROWS: ServiceRow[] = [
  { category: '手続き一式', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: '2/3はお客さんが広域交付制度で取得' },
  { category: '手続き一式', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: '10割オーシャン' },
  { category: '手続き一式', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '相関図', task: '相関図作成', owner: '自社', hint: '9割オーシャン' },
  { category: '手続き一式', gyomu: '法定相続情報取得', task: '法定相続情報一覧図の申出・取得', owner: '自社', hint: '9割オーシャン' },
  { category: '手続き一式', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: '9割以上オーシャンさん。 / 不動産はまとめて依頼が多い' },
  { category: '手続き一式', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: '9割以上オーシャンさん。' },
  { category: '手続き一式', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: '9割以上オーシャンさん。' },
  { category: '手続き一式', gyomu: '不動産', task: '査定の依頼', owner: '自社' },
  { category: '手続き一式', gyomu: '不動産', task: '不動産鑑定手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '不動産', task: '不動産売却サポート', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '金融資産', task: '全店調査', owner: '自社' },
  { category: '手続き一式', gyomu: '金融資産', task: '残高証明取得', owner: '自社' },
  { category: '手続き一式', gyomu: '金融資産', task: '取引履歴取得', owner: '自社' },
  { category: '手続き一式', gyomu: '金融資産', task: '証券保管振替機構照会', owner: '自社' },
  { category: '手続き一式', gyomu: '金融資産', task: '保険照会', owner: '自社' },
  { category: '手続き一式', gyomu: '金融資産', task: '年金照会', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '金融資産', task: '負債調査', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '目録', task: '財産目録の作成', owner: '自社' },
  { category: '手続き一式', gyomu: '協議書', task: '遺産分割協議書の作成', owner: '自社', hint: '10割オーシャン' },
  { category: '手続き一式', gyomu: '登記', task: '相続登記の申請', owner: '自社', hint: '10割オーシャン' },
  { category: '手続き一式', gyomu: '解約', task: '預貯金の解約', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '手続き一式', gyomu: '解約', task: '証券の移管・売却', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '手続き一式', gyomu: '解約', task: '投資信託の解約', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '手続き一式', gyomu: '解約', task: '自動車名義変更', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '解約', task: '保険金請求手続き', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '手続き一式', gyomu: '手紙', task: '各相続人への通知・案内文の送付', owner: '自社' },
  { category: '登記', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: '依頼者がやることが多い / 発生することはあまりない' },
  { category: '登記', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '登記', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '登記', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '登記', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '登記', gyomu: '相関図', task: '相関図作成', owner: '自社', hint: '半々' },
  { category: '登記', gyomu: '不動産', task: '不動産関連書類チェック', owner: '自社', hint: '依頼者がやることが多い' },
  { category: '登記', gyomu: '協議書', task: '協議書のチェック', owner: '自社' },
  { category: '登記', gyomu: '登記', task: '相続登記の申請', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3' },
  { category: '遺言', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '遺言', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '遺言', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '遺言', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '金融資産', task: '金融資産資料の確認', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '遺言作成', task: '遺言文案(自筆)作成', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '遺言作成', task: '遺言文案(公正証書)作成', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '遺言作成', task: '文案確認・公証役場訪問の日程調整', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '遺言作成', task: '公証役場訪問日程の共有', owner: '自社', hint: 'オーシャン' },
  { category: '遺言', gyomu: '遺言作成', task: '公正証書遺言作成', owner: '自社', hint: '依頼者、公証人の先生' },
  { category: '信託', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3' },
  { category: '信託', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '信託', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '信託', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '信託', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '金融資産', task: '金融資産資料の確認', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '信託契約書作成', task: '信託契約書案作成', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '信託契約書作成', task: '文案確認・公証役場訪問の日程調整', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '信託契約書作成', task: '公証役場訪問日程の共有', owner: '自社', hint: 'オーシャン' },
  { category: '信託', gyomu: '信託契約書作成', task: '信託契約書作成', owner: '自社', hint: '依頼者、公証人の先生' },
  { category: '信託', gyomu: '登記', task: '信託登記', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3 / いきなり放棄受注ケースもあるけど、手続き一式で財産調査した結果放棄になるケースが多い。' },
  { category: '放棄', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '放棄', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '放棄', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '放棄', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '金融資産', task: '金融資産資料の確認', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '放棄手続き', task: '放棄の申述書類作成', owner: '自社', hint: 'オーシャン / 家庭裁判所に提出する書類作成して、署名捺印依頼者から' },
  { category: '放棄', gyomu: '放棄手続き', task: '家庭裁判所へ申述', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '放棄手続き', task: '申述照会書受領', owner: '自社', hint: 'オーシャン / 指定できない。どっちに届くか' },
  { category: '放棄', gyomu: '放棄手続き', task: '申述照会書記載例提案', owner: '自社', hint: 'オーシャン' },
  { category: '放棄', gyomu: '放棄手続き', task: '申述照会書提出', owner: '自社', hint: '依頼者' },
  { category: '放棄', gyomu: '放棄手続き', task: '受理通知書の受領', owner: '自社', hint: '指定できない。どっちに届くか' },
  { category: '放棄', gyomu: '放棄手続き', task: '受理証明書の取得', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3 / もめちゃって紛争、ほとんどやらない' },
  { category: '調停', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '調停', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '調停', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '調停', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '金融資産', task: '金融資産資料の確認', owner: '自社', hint: 'オーシャン' },
  { category: '調停', gyomu: '調停手続き', task: '調停申し立て書類の作成', owner: '自社' },
  { category: '検認', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3 / 自筆証書遺言があったときに、家庭裁判所に遺言書あるよお墨付きある。検認したあとに手続き一式につながる。' },
  { category: '検認', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '検認', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '検認', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '検認', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '検認', gyomu: '検認手続き', task: '検認の申し立て書類作成', owner: '自社', hint: 'オーシャン / 家庭裁判所に提出する書類作成して、署名捺印依頼者から' },
  { category: '検認', gyomu: '検認手続き', task: '家庭裁判所へ検認申し立て', owner: '自社', hint: 'オーシャン' },
  { category: '検認', gyomu: '検認手続き', task: '検認期日の日程調整・同行案内', owner: '自社', hint: 'オーシャン / オーシャンさんは立ち会えないけど、一緒に行ってあげることがある' },
  { category: '検認', gyomu: '検認手続き', task: '同行', owner: '自社', hint: 'オーシャン' },
  { category: '検認', gyomu: '検認手続き', task: '検認済遺言書の受領', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン：依頼者＝6：4、7：3 / 後見単体はあまりない、判断能力のない認知症の相続人の代わりの後見人を立てる' },
  { category: '後見', gyomu: '戸籍', task: '戸籍チェック', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '後見', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '後見', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '後見', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '金融資産', task: '金融資産資料の確認', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '後見手続き', task: '後見申し立て書類の確認・取得　※診断書、親族からの同意書、状況確認書', owner: '自社' },
  { category: '後見', gyomu: '後見手続き', task: '後見の申し立て書類作成', owner: '自社', hint: 'オーシャン' },
  { category: '後見', gyomu: '後見手続き', task: '家庭裁判所へ後見申し立て', owner: '自社', hint: 'オーシャン' },
  { category: '契約書', gyomu: '契約書作成', task: '関係書類取得', owner: '自社' },
  { category: '契約書', gyomu: '契約書作成', task: '契約書類作成', owner: '自社' },
  { category: '執行', gyomu: '戸籍', task: '戸籍収集（請求・取得）', owner: '自社', hint: 'オーシャン' },
  { category: '執行', gyomu: '戸籍', task: '戸籍チェック', owner: '自社' },
  { category: '執行', gyomu: '戸籍', task: '戸籍郵送手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '戸籍', task: '戸籍到着確認・読み込み', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '戸籍', task: '追加戸籍請求', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '執行通知', task: '執行人通知', owner: '自社', hint: '相続人住所が分かった時点で、相続人確定した時点で、執行人ですよ。通知' },
  { category: '執行', gyomu: '相関図', task: '相関図作成', owner: '自社', hint: '9割オーシャン' },
  { category: '執行', gyomu: '法定相続情報取得', task: '法定相続情報一覧図の申出・取得', owner: '自社', hint: '9割オーシャン' },
  { category: '執行', gyomu: '不動産', task: '名寄帳請求', owner: '自社', hint: '9割以上オーシャンさん。不動産はまとめて依頼が多い' },
  { category: '執行', gyomu: '不動産', task: '登記事項証明の取得', owner: '自社', hint: '9割以上オーシャンさん。不動産はまとめて依頼が多い' },
  { category: '執行', gyomu: '不動産', task: '固定資産評価証明の取得', owner: '自社', hint: '9割以上オーシャンさん。不動産はまとめて依頼が多い' },
  { category: '執行', gyomu: '不動産', task: '査定の依頼', owner: '自社' },
  { category: '執行', gyomu: '不動産', task: '不動産鑑定手配', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '不動産', task: '不動産売却サポート', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '金融資産', task: '全店調査', owner: '自社' },
  { category: '執行', gyomu: '金融資産', task: '残高証明取得', owner: '自社' },
  { category: '執行', gyomu: '金融資産', task: '取引履歴取得', owner: '自社' },
  { category: '執行', gyomu: '金融資産', task: '証券保管振替機構照会', owner: '自社' },
  { category: '執行', gyomu: '金融資産', task: '保険照会', owner: '自社' },
  { category: '執行', gyomu: '金融資産', task: '年金照会', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '金融資産', task: '負債調査', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '目録', task: '財産目録の作成', owner: '自社' },
  { category: '執行', gyomu: '協議書', task: '遺産分割協議書の作成', owner: '自社', hint: '10割オーシャン' },
  { category: '執行', gyomu: '登記', task: '相続登記の申請', owner: '自社', hint: '10割オーシャン' },
  { category: '執行', gyomu: '解約', task: '預貯金の解約', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '執行', gyomu: '解約', task: '証券の移管・売却', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '執行', gyomu: '解約', task: '投資信託の解約', owner: '自社', hint: '半々くらい依頼者がやる' },
  { category: '執行', gyomu: '解約', task: '自動車名義変更', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '解約', task: '保険金請求手続き', owner: '自社', hint: '既存テンプレより（細かい手順）' },
  { category: '執行', gyomu: '手紙', task: '各相続人への通知・案内文の送付', owner: '自社' },
]

export function gyomuFor(category: string): string[] {
  const seen = new Set<string>(); const list: string[] = []
  for (const r of SERVICE_ROWS) if (r.category === category && !seen.has(r.gyomu)) { seen.add(r.gyomu); list.push(r.gyomu) }
  return list
}
export function tasksFor(category: string, gyomu: string): ServiceRow[] {
  return SERVICE_ROWS.filter(r => r.category === category && r.gyomu === gyomu)
}

// 区分非依存の業務（受注区分に関係なく使う）
export const CROSS_GYOMU_TAB: Record<string, TabKey | undefined> = { '経理': 'contract', '相続税': undefined }
export const KEIZAI_TASKS: string[] = ['分配金計算書作成','報酬請求書作成','入金確認','分配金送金実行','納品書類一式作成','案件クローズ処理']
export const ZEIRISHI_TASKS: string[] = ['相続税申告要否判定','相続税申告書類準備','税理士への引継ぎ']
